[Release] Add content security headers #165
cds-snc/resources-ressources pull request #166
Opened 2022-07-30 20:18 UTC by daine

# Summary | Résumé

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.

---

> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.

2022-08-02 16:31 UTC, anikbrazeau commented
I'm not sure I'm best placed to review/test this PR? What do you think @dylanzheng94?

Does this fix https://github.com/cds-snc/resources-ressources/issues/53? 🤔 
Are the accessibility checks failing a concern? 👀

2022-08-03 14:43 UTC, dylanzheng94 approved these changes

2022-08-03 17:31 UTC, dylanzheng94 commented on app/components/ResourceListItem.vue
> +    class="py-5 px-1.5 rounded-2xl mb-4 hover:bg-gray-100 cursor-pointer drop-shadow-2xl -mx-2 w-fit"
`w-fit` doesn't work as intended

2022-08-03 17:32 UTC, dylanzheng94 commented on app/components/Footer.vue
> +            class="text-gray-800 text-2xl font-medium hover:underline hover:text-blue-700 mb-1 w-fit"
`w-fit` doesn't work as intended

2022-08-03 17:33 UTC, dylanzheng94 requested changes
`w-fit` doesn't actually perform `style="width: fit-content"`
another solution is required

2022-08-03 19:33 UTC, dylanzheng94 approved these changes

2022-08-03 19:49 UTC, merged

2022-08-08 15:45 UTC, daine commented
> `w-fit` doesn't actually perform `style="width: fit-content"` another solution is required

Thanks for flagging this! The [Content Security Policy for styles](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src) doesn't like inline styles, so we might have to look further into this. I'm not seeing any errors right now on https://learning-resources.cdssandbox.xyz/ but I'll check our CSP report this week